apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: flask-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flask-container
        image: __IMAGE__  # <-- Jenkins will replace this with the actual image
        imagePullPolicy: Always  # Always pull the new image
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_APP
          value: "app.py"  
        - name: FLASK_RUN_HOST
          value: "0.0.0.0"
